### ISSUE TITLE
[BUG] - Safari rendering problemen

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-multiselect#118]
**Omschrijf het probleem**
Demo pagina lijkt niet te werken onder safari

**Hoe te reproduceren**
Open safari ga naar https://webcomponenten.omgeving.vlaanderen.be/demo/vl-multiselect.html

**Comment by coemans** [comment]
Probleem beperkt zich niet tot de demo pagina, er zijn algemeen rendering problemen in Safari.

**Comment by FreekRombauts** [comment]
@coemans , ziet er in orde uit nu.
