### ISSUE TITLE
[BUG] - Focus call heeft geen effect

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-multiselect#119]
**Omschrijf het probleem**
focus() call op de component heeft geen effect

**Hoe te reproduceren**
inspect de multi select component via bvb chrome dev tools, roep $0.focus() op

**Comment by FreekRombauts** [comment]
@coemans , getest en focus werkt, maar er is nu een nieuw probleem: Na het openen van een multiselect dropdown krijg je deze niet meer dicht:

* open een multiselect dropdown
* optioneel: selecteer 1 of meerdere items
* klik buiten de dropdown om hem te sluiten

verwacht: dropdown sluit
werkelijk: dropdown blijft open

* verwijder opnieuw een item
* klik buiten de dropdown. Nu werkt sluiten wel. Geen idee waarom dit wel werkt.

**Comment by coemans** [comment]
@FreekRombauts ik kan het probleem niet reproduceren, of ik doe misschien niet helemaal hetzelfde?

![focus](https://user-images.githubusercontent.com/11139249/96432086-aefe4280-1204-11eb-90c1-f21f79fc7f36.gif)
