### ISSUE TITLE
[BUG] - Geselecteerde keuzes zijn altijd ellipsis

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-multiselect#120]
**Omschrijf het probleem**
ongeacht de grootte van de label worden alle keuezes met ellipsis getoond

**Hoe te reproduceren**
selecteer een paar keuzes, ze komen allemaal tevoorschijn met ellipsis

**Gewenst gedrag**
ellipsis zou pas tevoorschijn mogen komen eens de label groter is dan x aantal pixels

**Comment by coemans** [comment]
Ik kan het probleem op de demo pagina niet reproduceren:

<img width="2560" alt="ellipsis" src="https://user-images.githubusercontent.com/11139249/96234830-4318a180-0f9a-11eb-9a60-602a64d9c711.png">

**Comment by SBylemans** [comment]
@coemans het is de combinatie van de vl-ui-pill styling met de multiselect.

**Comment by SBylemans** [comment]
@coemans heb een branch aangemaakt met het probleem in de demo pagina: https://github.com/milieuinfo/webcomponent-vl-ui-multiselect/tree/ellipsis-issue

**Comment by coemans** [comment]
Probleem is niet meer reproduceerbaar na upgrade van de huisstijl v4.0.9.
