### ISSUE TITLE
[BUG] - multiselect lijkt niet te werken op safari (op demo pagina)

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-multiselect#128]
**Omschrijf het probleem**
Bij het openen van de demo pagina voor de multiselect in safari, werkt deze niet.

Echter bij het gebruik van deze component binnen onze applicatie, werkt dit op het eerste zicht wel wanneer ik dit open doe in safari. 

**Hoe te reproduceren**
Surfen naar https://webcomponenten.omgeving.vlaanderen.be/demo/vl-multiselect.html

**Gewenst gedrag**
Dat dit werkt op de demo pagina om de voorbeelden te kunnen raadplegen.

**Screenshots**
<img width="1041" alt="Screenshot 2020-11-19 at 14 28 28" src="https://user-images.githubusercontent.com/8820456/99672304-8079be80-2a73-11eb-96e9-816935b28c4d.png">

**Omgeving (gelieve aan te vullen):**
 - Browser safari
 - Versie 13.1.1 (15609.2.9.1.2)
 - Versie component 3.2.2 (in onze applicatie dan toch)

**Comment by coemans** [comment]
Aangezien de demo pagina achterliggend de BOM gebruikt, is deze niet altijd helemaal up to date omdat de BOM slechts frequent gereleased wordt. Ik vermoed dat dit een duplicate is van #118 dus sluit ik het issue af. Anders geef je maar een seintje.
