### ISSUE TITLE
[BUG] - Als de geselecteerde tekst lang is, wordt dit niet goed weergegeven bij de multiselect

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-multiselect#54]
**Omschrijf het probleem**
Weergave is niet mooi, zie screenshot

**Hoe te reproduceren**
Select met item met lange tekst

**Gewenst gedrag**
Beter is misschien afkorten (...) zoals op andere plaatsen

**Screenshots**

![image](https://user-images.githubusercontent.com/29454303/68206829-f973b880-ffcd-11e9-86ce-35529b271a7e.png)

**Omgeving (gelieve aan te vullen):**
 - Browser Firefox
 - Versie 71.0b5 (64-bit)
 - Versie component 1.0.1

**Extra info**

**Comment by coemans** [comment]
Probleem is ook reproduceerbaar bij Webuniversum, ik zal dit melden.

**Comment by coemans** [comment]
Het probleem stelt zich blijkbaar nog steeds bij de laatste versie van Webuniversum. Ik denk dat we daarom best zelf een PR voorzien bij Webuniversum met een oplossing zodat dit probleem in een volgende versie opgelost wordt. De fix kan dan tijdelijk ook bij ons toegepast worden zodat afnemers er verder geen last van hebben.

Voor de planning verwijs ik naar @kevcraey.
