### ISSUE TITLE
[BUG] - Z-index problemen in combinatie met andere componenten

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-multiselect#58]
**Omschrijf het probleem**
Andere componenten komen boven de dropdown van de multiselect te staan. Dit is getest met datepicker, upload, select en multiselect component.

**Hoe te reproduceren**
Maak een form met een multiselect boven een datepicker bvb.

**Gewenst gedrag**
Dropdown van de multiselect moet helemaal vanboven komen te staan

**Screenshots**
![image](https://user-images.githubusercontent.com/5136671/69056335-0baf1700-0a10-11ea-8f81-858d7a80ae45.png)

Datepicker knop komt boven de dropdown.

**Omgeving (gelieve aan te vullen):**
 - Browser chrome, safari
 - Versie LATEST
 - Versie component 2.0.0

**Comment by pharacyde** [comment]
is deze issue niet gerelateerd aan https://github.com/milieuinfo/webcomponent-vl-ui-select/issues/57 ?

**Comment by coemans** [comment]
Het is ook een z-index probleem, maar verder niet echt een relatie. De fix in https://github.com/milieuinfo/webcomponent-vl-ui-select/issues/57 was niet voldoende voor dit probleem. Het is in combinatie met een andere webcomponent, dus vermoedelijk moet de z-index nog hoger gezet worden.
